<a href="https://colab.research.google.com/github/mariettarosemathew-ui/Assesment_numpypanda_Marietta/blob/main/Assesment_numpypanda_Marietta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
import numpy as np

In [3]:
num=np.array([10,20,30,40,50])
print(num)
print(num.shape)
print(num.dtype)

[10 20 30 40 50]
(5,)
int64


Q2

In [5]:
arr=np.array([5,10,15,20,25])
print(arr+5)
print(arr*2)

[10 15 20 25 30]
[10 20 30 40 50]


Q3

In [58]:
arr=np.array([12,15,18,20,25,30])
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("maximum:",np.max(arr))
print("minimum:",np.min(arr))
print("standard deviation:",np.std(arr))

mean: 20.0
median: 19.0
maximum: 30
minimum: 12
standard deviation: 6.027713773341708


Q4

In [7]:
arr=np.array([10, 25, 30, 45, 50, 65, 70])
print(arr[arr>40])

[45 50 65 70]


Q5

In [8]:
import pandas as pd

In [13]:
df=pd.DataFrame({
    "Name":["Anu","Rahul","Meera","Arun"],
    "Age":[21,22,20,23],
    "Score":[85,72,91,68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68


Q6

In [20]:
df[["Name","Score"]]


,Name,Score
0,Anu,85
1,Rahul,72
2,Meera,91
3,Arun,68


In [21]:
df[df["Name"]=="Meera"]

,Name,Age,Score
2,Meera,20,91


Q7

In [22]:
df[df["Score"]>75]

,Name,Age,Score
0,Anu,21,85
2,Meera,20,91


Q8

In [26]:
print("Shape:")
print(df.shape)
print("\nColumn names:")
print(df.columns)
print("\nData types:")
print(df.dtypes)
print("\nStatistical summary:")
print(df.describe())

Shape:
(4, 3)

Column names:
Index(['Name', 'Age', 'Score'], dtype='object')

Data types:
Name     object
Age       int64
Score     int64
dtype: object

Statistical summary:
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000


Q9

In [29]:
df=df.sort_values(by="Score",ascending=False)
df

,Name,Age,Score
2,Meera,20,91
0,Anu,21,85
1,Rahul,22,72
3,Arun,23,68


Q10

In [32]:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})
print("Missing values:")
print(df.isnull())
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Score"]=df["Score"].fillna(df["Score"].mean())
print(df)

Missing values:
    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000


Q11

In [33]:
student_performance='/content/drive/MyDrive/DSA Class/Datasets/student_performance.csv'
df=pd.read_csv(student_performance)
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4


In [37]:
print("First 5 records:")
print(df.head())
print("Last 5 records:")
print(df.tail())
print("Number of rows and columns:")
print(df.shape)
print("Column names:")
print(df.columns)
print("Data types:")
print(df.dtypes)
print("Statistical summary:")
print(df.describe())

First 5 records:
  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7   
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5   
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5   
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4   
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4   

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  
0          89.4       86.3          81.9         76.7         82.7  
1          70.3       63.1          65.1         62.3         60.3  
2          79.9       80.4          65.3         68.0         67.1  
3          65.8       50.7          52.6         48.8         57.2  
4          90.1       82.9          72.4         87.7         81.9  
Last 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     P

Q12

In [39]:
df[df["Final_Score"]>75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7


In [40]:
df[df["Attendance"]<75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4


In [43]:
df[(df["Department"]=="Data Science")&(df["Final_Score"]>80)]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9


In [46]:
df.sort_values(by="Final_Score",ascending=False)


,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN


Q13

In [56]:
import pandas as pd
import numpy as np
df=pd.read_csv(student_performance)
df_subset=df.head(6).copy()
df_subset["Python_Score"]=[95, 70, 88, 55, 92, 78]
df_subset["SQL_Score"]=[90, 75, 85, 60, 94, 72]
df_subset["Pandas_Score"]=[88, 72, 91, 58, 89, 75]
df_subset["NumPy_Score"]=[92, 68, 87, 62, 90, 74]
df_subset["Average_Technical_Score"]=(
    df_subset["Python_Score"]
    + df_subset["SQL_Score"]
    + df_subset["Pandas_Score"]
    + df_subset["NumPy_Score"]
) / 4
conditions=[
    df_subset["Average_Technical_Score"]>=90,
    df_subset["Average_Technical_Score"]>=75,
    df_subset["Average_Technical_Score"]>=60
]
choices=[
    "Excellent",
    "Good",
    "Average"
]
df_subset["Performance"]=np.select(
    conditions,
    choices,
    default="Needs Improvement"
)
print(df_subset)

  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7   
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5   
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5   
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4   
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4   
5    STU1006      Diya Reddy    Male     Data Science   22.0        76.7   

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0            95         90            88           92         82.7   
1            70         75            72           68         60.3   
2            88         85            91           87         67.1   
3            55         60            58           62         57.2   
4            92         94            89           90         81.9   
5            78         72            75       

Q14

In [55]:
newdepartment=df.groupby("Department").agg(
    Number_of_Students=("Student_ID", "count"),
    Average_Final_Score=("Final_Score", "mean"),
    Maximum_Final_Score=("Final_Score", "max"),
    Minimum_Final_Score=("Final_Score", "min")
)
newdepartment=newdepartment .sort_values(
    by="Average_Final_Score",
    ascending=False
)
print(newdepartment )

                  Number_of_Students  Average_Final_Score  \
Department                                                  
Electronics                       13            72.846154   
Computer Science                  29            71.479310   
Data Science                      27            71.324000   
Commerce                           8            67.825000   
data science                       1            66.900000   
 Data Science                      1            55.100000   
Computer science                   1            46.700000   

                  Maximum_Final_Score  Minimum_Final_Score  
Department                                                  
Electronics                      86.9                 51.2  
Computer Science                 96.0                 40.6  
Data Science                     97.0                 43.5  
Commerce                         83.7                 54.6  
data science                     66.9                 66.9  
 Data Science          

Q15

In [63]:
import numpy as np
score=df["Final_Score"].to_numpy()
mean_score=np.mean(score)
print("Mean:", mean_score)
print("Median:", np.median(score))
print("Standard deviation:", np.std(score))
print("25th percentile:", np.percentile(score, 25))
print("75th Percentile:", np.percentile(score, 75))
print("Students above overall mean:")
df[df["Final_Score"] > mean_score]

Mean: nan
Median: nan
Standard deviation: nan
25th percentile: nan
75th Percentile: nan
Students above overall mean:


,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score


Q16